/*
 * Created on 2019-10-24 ( Time 19:31:50 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.et.informate.backend.informatebackend.app.dominio;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "computo"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="computo", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Computo.countAll", query="SELECT COUNT(x) FROM Computo x" )
} )
public class Computo implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="pais_vc", length=200)
    private String     pais         ;

    @Column(name="num_dep_nb")
    private Integer    numDep       ;

    @Column(name="nom_dep_vc", length=200)
    private String     nomDep       ;

    @Column(name="nom_prov_vc", length=200)
    private String     nomProv      ;

    @Column(name="num_mun_nb")
    private Integer    numMun       ;

    @Column(name="nom_mun_vc", length=200)
    private String     nomMun       ;

    @Column(name="circunscripcion_nb")
    private Integer    circunscripcion ;

    @Column(name="localidad_vc", length=200)
    private String     localidad    ;

    @Column(name="recinto_vc", length=200)
    private String     recinto      ;

    @Column(name="num_mesa_nb")
    private Integer    numMesa      ;

    @Column(name="cod_mesa_nb")
    private BigDecimal codMesa      ;

    @Column(name="eleccion", length=200)
    private String     eleccion     ;

    @Column(name="inscritos_nb")
    private Integer    inscritos    ;

    @Column(name="cc_nb")
    private Integer    cc           ;

    @Column(name="fpv_nb")
    private Integer    fpv          ;

    @Column(name="mts_nb")
    private Integer    mts          ;

    @Column(name="ucs_nb")
    private Integer    ucs          ;

    @Column(name="mas_nb")
    private Integer    mas          ;

    @Column(name="21f_nb")
    private Integer    _21f          ;

    @Column(name="pdc_nb")
    private Integer    pdc          ;

    @Column(name="mnr_nb")
    private Integer    mnr          ;

    @Column(name="panbol_nb")
    private Integer    panbol       ;

    @Column(name="votos_validos_nb")
    private Integer    votosValidos ;

    @Column(name="blancos_nb")
    private Integer    blancos      ;

    @Column(name="nulos_nb")
    private Integer    nulos        ;

    @Column(name="estado_acta_vc", length=200)
    private String     estadoActa   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Computo() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : pais_vc ( varchar ) 
    public void setPais( String pais ) {
        this.pais = pais;
    }
    public String getPais() {
        return this.pais;
    }

    //--- DATABASE MAPPING : num_dep_nb ( int4 ) 
    public void setNumDep( Integer numDep ) {
        this.numDep = numDep;
    }
    public Integer getNumDep() {
        return this.numDep;
    }

    //--- DATABASE MAPPING : nom_dep_vc ( varchar ) 
    public void setNomDep( String nomDep ) {
        this.nomDep = nomDep;
    }
    public String getNomDep() {
        return this.nomDep;
    }

    //--- DATABASE MAPPING : nom_prov_vc ( varchar ) 
    public void setNomProv( String nomProv ) {
        this.nomProv = nomProv;
    }
    public String getNomProv() {
        return this.nomProv;
    }

    //--- DATABASE MAPPING : num_mun_nb ( int4 ) 
    public void setNumMun( Integer numMun ) {
        this.numMun = numMun;
    }
    public Integer getNumMun() {
        return this.numMun;
    }

    //--- DATABASE MAPPING : nom_mun_vc ( varchar ) 
    public void setNomMun( String nomMun ) {
        this.nomMun = nomMun;
    }
    public String getNomMun() {
        return this.nomMun;
    }

    //--- DATABASE MAPPING : circunscripcion_nb ( int4 ) 
    public void setCircunscripcion( Integer circunscripcion ) {
        this.circunscripcion = circunscripcion;
    }
    public Integer getCircunscripcion() {
        return this.circunscripcion;
    }

    //--- DATABASE MAPPING : localidad_vc ( varchar ) 
    public void setLocalidad( String localidad ) {
        this.localidad = localidad;
    }
    public String getLocalidad() {
        return this.localidad;
    }

    //--- DATABASE MAPPING : recinto_vc ( varchar ) 
    public void setRecinto( String recinto ) {
        this.recinto = recinto;
    }
    public String getRecinto() {
        return this.recinto;
    }

    //--- DATABASE MAPPING : num_mesa_nb ( int4 ) 
    public void setNumMesa( Integer numMesa ) {
        this.numMesa = numMesa;
    }
    public Integer getNumMesa() {
        return this.numMesa;
    }

    //--- DATABASE MAPPING : cod_mesa_nb ( numeric ) 
    public void setCodMesa( BigDecimal codMesa ) {
        this.codMesa = codMesa;
    }
    public BigDecimal getCodMesa() {
        return this.codMesa;
    }

    //--- DATABASE MAPPING : eleccion ( varchar ) 
    public void setEleccion( String eleccion ) {
        this.eleccion = eleccion;
    }
    public String getEleccion() {
        return this.eleccion;
    }

    //--- DATABASE MAPPING : inscritos_nb ( int4 ) 
    public void setInscritos( Integer inscritos ) {
        this.inscritos = inscritos;
    }
    public Integer getInscritos() {
        return this.inscritos;
    }

    //--- DATABASE MAPPING : cc_nb ( int4 ) 
    public void setCc( Integer cc ) {
        this.cc = cc;
    }
    public Integer getCc() {
        return this.cc;
    }

    //--- DATABASE MAPPING : fpv_nb ( int4 ) 
    public void setFpv( Integer fpv ) {
        this.fpv = fpv;
    }
    public Integer getFpv() {
        return this.fpv;
    }

    //--- DATABASE MAPPING : mts_nb ( int4 ) 
    public void setMts( Integer mts ) {
        this.mts = mts;
    }
    public Integer getMts() {
        return this.mts;
    }

    //--- DATABASE MAPPING : ucs_nb ( int4 ) 
    public void setUcs( Integer ucs ) {
        this.ucs = ucs;
    }
    public Integer getUcs() {
        return this.ucs;
    }

    //--- DATABASE MAPPING : mas_nb ( int4 ) 
    public void setMas( Integer mas ) {
        this.mas = mas;
    }
    public Integer getMas() {
        return this.mas;
    }

    //--- DATABASE MAPPING : 21f_nb ( int4 ) 
    public void set21f( Integer _21f ) {
        this._21f = _21f;
    }
    public Integer get21f() {
        return this._21f;
    }

    //--- DATABASE MAPPING : pdc_nb ( int4 ) 
    public void setPdc( Integer pdc ) {
        this.pdc = pdc;
    }
    public Integer getPdc() {
        return this.pdc;
    }

    //--- DATABASE MAPPING : mnr_nb ( int4 ) 
    public void setMnr( Integer mnr ) {
        this.mnr = mnr;
    }
    public Integer getMnr() {
        return this.mnr;
    }

    //--- DATABASE MAPPING : panbol_nb ( int4 ) 
    public void setPanbol( Integer panbol ) {
        this.panbol = panbol;
    }
    public Integer getPanbol() {
        return this.panbol;
    }

    //--- DATABASE MAPPING : votos_validos_nb ( int4 ) 
    public void setVotosValidos( Integer votosValidos ) {
        this.votosValidos = votosValidos;
    }
    public Integer getVotosValidos() {
        return this.votosValidos;
    }

    //--- DATABASE MAPPING : blancos_nb ( int4 ) 
    public void setBlancos( Integer blancos ) {
        this.blancos = blancos;
    }
    public Integer getBlancos() {
        return this.blancos;
    }

    //--- DATABASE MAPPING : nulos_nb ( int4 ) 
    public void setNulos( Integer nulos ) {
        this.nulos = nulos;
    }
    public Integer getNulos() {
        return this.nulos;
    }

    //--- DATABASE MAPPING : estado_acta_vc ( varchar ) 
    public void setEstadoActa( String estadoActa ) {
        this.estadoActa = estadoActa;
    }
    public String getEstadoActa() {
        return this.estadoActa;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(pais);
        sb.append("|");
        sb.append(numDep);
        sb.append("|");
        sb.append(nomDep);
        sb.append("|");
        sb.append(nomProv);
        sb.append("|");
        sb.append(numMun);
        sb.append("|");
        sb.append(nomMun);
        sb.append("|");
        sb.append(circunscripcion);
        sb.append("|");
        sb.append(localidad);
        sb.append("|");
        sb.append(recinto);
        sb.append("|");
        sb.append(numMesa);
        sb.append("|");
        sb.append(codMesa);
        sb.append("|");
        sb.append(eleccion);
        sb.append("|");
        sb.append(inscritos);
        sb.append("|");
        sb.append(cc);
        sb.append("|");
        sb.append(fpv);
        sb.append("|");
        sb.append(mts);
        sb.append("|");
        sb.append(ucs);
        sb.append("|");
        sb.append(mas);
        sb.append("|");
        sb.append(21f);
        sb.append("|");
        sb.append(pdc);
        sb.append("|");
        sb.append(mnr);
        sb.append("|");
        sb.append(panbol);
        sb.append("|");
        sb.append(votosValidos);
        sb.append("|");
        sb.append(blancos);
        sb.append("|");
        sb.append(nulos);
        sb.append("|");
        sb.append(estadoActa);
        return sb.toString(); 
    } 

}
