/*
 * Created on 2019-10-24 ( Time 19:31:50 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.et.informate.backend.informatebackend.app.dominio;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "departamento"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="departamento", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Departamento.countAll", query="SELECT COUNT(x) FROM Departamento x" )
} )
public class Departamento implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="num_dep_nb", nullable=false)
    private Integer    numDep       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nom_dep_vc", length=255)
    private String     nomDep       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Departamento() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setNumDep( Integer numDep ) {
        this.numDep = numDep ;
    }
    public Integer getNumDep() {
        return this.numDep;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nom_dep_vc ( varchar ) 
    public void setNomDep( String nomDep ) {
        this.nomDep = nomDep;
    }
    public String getNomDep() {
        return this.nomDep;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(numDep);
        sb.append("]:"); 
        sb.append(nomDep);
        return sb.toString(); 
    } 

}
