/*
 * Created on 2019-10-24 ( Time 19:31:50 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.et.informate.backend.informatebackend.app.dominio;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "pais"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="pais", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Pais.countAll", query="SELECT COUNT(x) FROM Pais x" )
} )
public class Pais implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="num_pais_nb", nullable=false)
    private Integer    numPais      ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nom_pais_vc", length=2147483647)
    private String     nomPais      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Pais() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setNumPais( Integer numPais ) {
        this.numPais = numPais ;
    }
    public Integer getNumPais() {
        return this.numPais;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nom_pais_vc ( varchar ) 
    public void setNomPais( String nomPais ) {
        this.nomPais = nomPais;
    }
    public String getNomPais() {
        return this.nomPais;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(numPais);
        sb.append("]:"); 
        sb.append(nomPais);
        return sb.toString(); 
    } 

}
