/*
 * Created on 2019-10-24 ( Time 19:31:50 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.et.informate.backend.informatebackend.app.dominio;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "provincia"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="provincia", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Provincia.countAll", query="SELECT COUNT(x) FROM Provincia x" )
} )
public class Provincia implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="num_prov_nb", nullable=false)
    private Integer    numProv      ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="num_dep_nb")
    private Integer    numDep       ;

    @Column(name="nom_prov_vc", length=200)
    private String     nomProv      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Provincia() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setNumProv( Integer numProv ) {
        this.numProv = numProv ;
    }
    public Integer getNumProv() {
        return this.numProv;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : num_dep_nb ( int4 ) 
    public void setNumDep( Integer numDep ) {
        this.numDep = numDep;
    }
    public Integer getNumDep() {
        return this.numDep;
    }

    //--- DATABASE MAPPING : nom_prov_vc ( varchar ) 
    public void setNomProv( String nomProv ) {
        this.nomProv = nomProv;
    }
    public String getNomProv() {
        return this.nomProv;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(numProv);
        sb.append("]:"); 
        sb.append(numDep);
        sb.append("|");
        sb.append(nomProv);
        return sb.toString(); 
    } 

}
